apiVersion: v1
kind: Service
metadata:
  name: knowix-frontend
spec:
  selector:
    app: knowix-frontend
  ports:
  - port: 8082
    targetPort: 8082
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowix-frontend
spec:
  selector:
    matchLabels:
      app: knowix-frontend
  template:
    metadata:
      labels:
        app: knowix-frontend
    spec:
      containers:
      - name: knowix-frontend
        image: us-central1-docker.pkg.dev/knowix-421914/knowix-repo/knowix_frontend
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8082
